version: '3'

services:
  nginx:
     image: nginx:1.21.3-alpine
     container_name: nginx
     ports:
       - 9000:80
     depends_on:
       - fastapi
     volumes:
       - ./nginx/nginx_development.conf:/etc/nginx/conf.d/default.conf


  fastapi:
     container_name: fastapi
     build: ./fastapi
     command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
     ports: 
       - 8000:8000
     volumes:
       - ./fastapi:/code/app
  
