version: '3'

services:
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - 9000:80
    depends_on:
      - fastapi
    volumes:
      - ./nginx/nginx_development.conf:/etc/nginx/conf.d/default.conf

  redis:
    container_name: redis
    image: redis:7
    ports:
      - '6379:6379'

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mobilitydb
    volumes:
      - pg_data:/var/lib/postgresql/data

  fastapi:
    container_name: fastapi
    build: ./fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    volumes:
      - ./fastapi:/code
  worker:
    container_name: worker
    build: ./fastapi
    command: celery -A celery_worker worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./fastapi:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - fastapi
      - redis

  flower:
    container_name: flower
    build: ./fastapi
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - fastapi
      - redis
      - worker

volumes:
  pg_data:
