name: Test fastapi and nginx smoke tests

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main.yml'
      - './fastapi/*'
      - './nginx/*'

jobs:
  docker:
    name: Docker FastAPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the docker-compose stack
        run: |
          docker-compose up -d && sleep 2 && docker ps

      - name: Curl request to nginx
        run: |
          curl -s -o /dev/null -w "%{http_code}" -X GET --insecure "http://localhost:9000/" && docker logs nginx && docker logs fastapi

      - name: Test that the application is running
        run: |
          cd ./fastapi && chmod +x smoke-test.sh && ./smoke-test.sh

      - name: Test to insert users
        run: |
          cd ./fastapi && chmod +x insert-users.sh && ./insert-users.sh

      - name: Test to get users
        run: |
          cd ./fastapi && chmod +x get-users.sh && ./get-users.sh

      - name: Test to create a celery task
        run: |
          cd ./fastapi && chmod +x create-celery-task.sh && ./create-celery-task.sh

      - name: Tear Down Docker Compose Stack
        run: |
          docker-compose down

# Adding CORS
