name: Test fastapi and nginx smoke tests

on: 
  push:
    branches:
      - main
    paths:
      - ".github/workflows/main.yml"
      - "./fastapi/*"
      - "./nginx/*"
  
jobs: 
  docker:
    name: Docker FastAPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the docker-compose stack
        run: |
          docker-compose up -d && sleep 2 && docker ps

      - name: Curl request to nginx
        run: |
          curl -s -o /dev/null -w "%{http_code}" -X GET --insecure "http://localhost:9000/" && docker logs nginx && docker logs fastapi    

      - name: Run smoke test
        run: |
          cd ./fastapi && chmod +x smoke-test.sh && ./smoke_test.sh
 
      - name: Tear Down Docker Compose Stack
        run: |
          docker-compose down

# Run me 
